In [62]:
print("Hello Data World")

Hello Data World


<img src="images/py.png" id="string" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

# Strings
***

Strings are used in Python to record text information, such as name. Strings in Python are actually a *sequence*, which basically means Python keeps track of every element in the string as a sequence. For example, Python understands the string "Python' to be a sequence of letters in a specific order. This means we will be able to use indexing to grab particular letters (like the first letter, or the last letter).

<img src="images/python_string.png" id="string" alt="Concept-Alert" style="float:center; "/>
<br/>
<br/>


This idea of a sequence is an important one in Python and we will touch upon it later on in the future.

In this lecture we'll learn about the following:

    1.) Creating Strings
    2.) Printing Strings
    3.) String Indexing and Slicing
    4.) String Properties
    5.) String Methods
    6.) Print Formatting

In [63]:
print("hello")
print() #line space
print("hello world")

hello

hello world


In [64]:
str1 = "hello"
str2 = "world"
# str1[0]
# str1[1]
# str1[2]
# str1[3]
# str1[4]
str1[-5]
str1[-4]
str1[-3]
str1[-2]
str1[-1]
print(str1+' '+str2)
# print(str1 * 10)
print('-' * 10)

hello world
----------




## String Slicing & Indexing
***
**String Indexing** is used to to select the letter at a particular index/position. 

**String Slicing** is a process to select a subset of an entire string

<img src="images/string-slicing-in-python.png" alt="Concept-Alert" style="float:center;" width="600px" height="400px"/> 
<br /> 

The examples of the above stated are as follows

In [65]:
s = "Namaste world"
s[0] # indexing
s[0:7] # slicing
s[0:] # slicing 0 to end
# s[0:7:2] # slicing with step
print('world' in s) # checking if a string is present in another string

True


### **Basic Built in String Python Functions**

In [66]:
a = "hello world"

print(a.upper())
print(a.lower())
print(type(a))

HELLO WORLD
hello world
<class 'str'>


In [67]:
# Formattig

name = "Manan"
age = 25
married = False

print("My name is %s and I am %d years old. %s" % (name, age,married))
print("My name is {} and I am {} years old. {}".format(name, age,married))

print(f"My name is {name} and I am {age} years old. {married}")

My name is Manan and I am 25 years old. False
My name is Manan and I am 25 years old. False
My name is Manan and I am 25 years old. False


# Working with Numbers

In [68]:
#Int and float 

print(2+3)
print(type(2+3)) 
print(type(2+3.2)) 

5
<class 'int'>
<class 'float'>


In [69]:
2 + 10 * 10 + 3

105

In [70]:
15 * 2 + 10

40

In [71]:
a = 10 
b = 20 
#mean means average
mean = (a + b) / 2 
print(mean)

15.0




# Lists
***
Lists can be thought of the most general version of a *sequence* in Python. 

In this section we will learn about:
    
    1.) Creating lists
    2.) Indexing and Slicing Lists
    3.) Basic List Methods
    4.) Nesting Lists
    5.) Introduction to List Comprehensions
    
<img src="images/python-list.jpeg" id="list" alt="Concept-Alert" style="float:center; margin-right:15px" width="700px" height="400px"/>
<br /> 

Lists are constructed with brackets [] and commas separating every element in the list.

Let's go ahead and see how we can construct lists!

In [72]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list3 = [11,12,13,14,15]

list4 = [list1,list2,list3]
print(list4)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]


#### Adding element 

In [73]:
l = [1,2,2.3,"one",'h']
l.append('e')
print(l)

[1, 2, 2.3, 'one', 'h', 'e']


Difference between append and extend

In [74]:
l =  [1,2,3]
print(l)
#now if i append and list 
l.append([4,5,6])
print(l)

#look at the output it has whole list as an single index
print(l[3])
# it just append the item not extent the list 

[1, 2, 3]
[1, 2, 3, [4, 5, 6]]
[4, 5, 6]


In [75]:
l = [1,2,3]
l.extend([4,5,6])
l
# now look at the output it extend list 

[1, 2, 3, 4, 5, 6]

In [76]:
l = list(range(10))
l
l[0:2]
l[0:10:2] #start:end:step



[0, 2, 4, 6, 8]


# Dictionaries
***
Now we're going to switch gears and learn about *mappings* called *dictionaries* in Python. If you're familiar with other languages you can think of these Dictionaries as hash tables. 

This section will serve as a brief introduction to dictionaries and consist of:

    1.) Constructing a Dictionary
    2.) Accessing objects from a dictionary
    3.) Nesting Dictionaries
    4.) Basic Dictionary Methods

<img src="images/dictionaries-in-python.jpeg" id = "dict" alt="Concept-Alert" style="float:center; margin-right:15px" width="600" height="400"/>
<br /> 

A Python dictionary consists of a key and then an associated value. That value can be almost any Python object.


## Constructing a Dictionary
Let's see how we can construct dictionaries to get a better understanding of how they work!

In [77]:
d = dict()
d['name'] = 'Manan'
d['age'] = 25
d['city'] = 'New Delhi'
print(d)

#################################
d2 = {'name': 'Manan', 'age': 25, 'city': 'New Delhi'}
d2

{'name': 'Manan', 'age': 25, 'city': 'New Delhi'}


{'name': 'Manan', 'age': 25, 'city': 'New Delhi'}

In [78]:
d2 = {'name': 'Manan', 'age': 25, 'city': 'New Delhi'}
d2['name'] == 'Manan'

d3 = {'name': 'Manan', 'age': [25,23,2], 'city': ['New Delhi', 'Mumbai']}
d3['age']

d3['age'][0]

d3['name'] += 'Pujara'
d3

d3['contact'] = {'phone': '9876543210', 'email': 'manan@gmail.com'}
d3

{'name': 'MananPujara',
 'age': [25, 23, 2],
 'city': ['New Delhi', 'Mumbai'],
 'contact': {'phone': '9876543210', 'email': 'manan@gmail.com'}}

# Set and Booleans
***
There are two other object types in Python that we should quickly cover. Sets and Booleans. 

## Sets

Sets are an unordered collection of *unique* elements. We can construct them by using the set() function. Let's go ahead and make a set to see how it works

#### Set Theory
<img src="images/sets2.png" width="40%"/>

In [79]:
l = [1,1,1,2,2,2,2,2,4,4,4,4]
l

[1, 1, 1, 2, 2, 2, 2, 2, 4, 4, 4, 4]

In [80]:
l_set = set(l)
l_set

{1, 2, 4}

##### Look above output set remove duplicate values

In [81]:
s = set()
s.add(1)
s

{1}

In [82]:
s.add(2)
s.add(3)
s

{1, 2, 3}

In [83]:
s.add(2)
s
# it will not add the number 2 to the set

{1, 2, 3}


# Python Tuples
***
Tuples are used to store multiple items in a single variable.

Tuple is one of 4 built-in data types in Python used to store collections of data, the other 3 are List, Set, and Dictionary, all with different qualities and usage.

A tuple is a collection which is ordered and unchangeable.

Tuples are written with round brackets.

In [84]:
t = (1,2,2,2,2,3,4,5,6,7,8,9,10)
t
print(type(t))


<class 'tuple'>


Tuple items are ordered, unchangeable, and allow duplicate values.

Tuple items are indexed, the first item has index [0], the second item has index [1] etc.

<img src='images/data_struc.png' width="800">

## Comprehensions
***
- Python provides syntactic sugar to write small loops to generate lists/sets/tuples/dicts in one line
- These are called comprehensions, and can greatly increase development speed and readability

Syntax:
```
    sequence = [expression(element) for element in iterable if condition]
```

The brackets used for creating the comprehension define what type of object is created.

Use **[ ]** for lists, **()** for _generators_, **{}** for sets and dicts

In [85]:
names = ['John', 'Mary', 'Peter', 'Paul', 'George', 'Ringo']
for name in names:
    print(f"hello {name}")



hello John
hello Mary
hello Peter
hello Paul
hello George
hello Ringo


In [86]:
names = ['John', 'Mary', 'Peter', 'Paul', 'George', 'Ringo']
hello = ['hello '+ name for name in names]
hello

['hello John',
 'hello Mary',
 'hello Peter',
 'hello Paul',
 'hello George',
 'hello Ringo']

In [87]:
nums = [1,2,3,4,5,6,7,8,9,10]
num_even =[num for num in nums if num%2==0]
print(num_even)


nums = [1,2,3,4,5,6,7,8,9,10]
num_odd =[num for num in nums if num%2!=0]
print(num_odd)


[2, 4, 6, 8, 10]
[1, 3, 5, 7, 9]


In [88]:
nums = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]

squerenum = [num * num for num in nums]
squerenum

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

## Exception Handling
***
#### try and except

The basic terminology and syntax used to handle errors in Python is the **try** and **except** statements. The code which can cause an exception to occue is put in the *try* block and the handling of the exception is the implemented in the *except* block of code. The syntax form is:

<img src="images/try_except_else_finally.webp" width="50%">

We can also just check for any exception with just using except: To get a better understanding of all this lets check out an example: We will look at some code that opens and writes a file:

In [89]:
try:
    1/0
except ZeroDivisionError:
    print("Divide by zero")
    

Divide by zero


<img src="images/exception.png" width="50%">


## File I/O : Helps you read your files
***
- Python provides a `file` object to read text/binary files.
- This is similar to the `FileStream` object in other languages.
- Since a `file` is a resource, it must be closed after use. This can be done manually, or using a context manager (**`with`** statement)

<div class="alert alert-block alert-info">Create a file in the current directory</div>

In [90]:
with open("myfile.txt",'w') as f:
    f.write("This is My File \n")
    f.write("boom baam \n")

In [91]:
with open("myfile.txt",'a') as f:
    f.write("This is appended content \n")
    f.write("boom baam")

In [92]:
# let's verify if it was really created.
# For that, let's find out which directory we're working from

import os
print(os.path.abspath(os.curdir)) #os->path->absoulate path-> os.cureentdir

/home/manan/DataEnginnerProjects/Py_For_DataEnginner


<div class="alert alert-block alert-info">Read the newly created file</div>

In [93]:
with open("myfile.txt",'r') as f:
    for line in f:
        print(line)

This is My File 

boom baam 

This is appended content 

boom baam


In [94]:
f.close()

In [95]:
with open("myfile.txt",'r') as f:
    for line in f:
        print(line)

This is My File 

boom baam 

This is appended content 

boom baam


# Lambda Function

##### it's just simpler version to make function in variable like you don;t need to write def and all thing

In [96]:
lambda_squere = lambda num:num**2
lambda_squere(2)

4

In [97]:
def squere(num):
    return num**2

squere(2)


4

# OOP 

- objects
- class
- attribute methon 
- special methods

## Object
look below we have all data type classes and we creating objects of it 

In [98]:
s = "manan"
i = 2
print(type(s))
print(type(i))
print(type([]))
print(type(()))
print(type({}))

<class 'str'>
<class 'int'>
<class 'list'>
<class 'tuple'>
<class 'dict'>


- we see that datatypes classes are pre defined or they already made by someone but let's see how we make our own class and make object of that

In [99]:
class Example:
    pass

x = Example()
print(type(x))

<class '__main__.Example'>


## Attribute 
it's what the object has like 
- Sudent class
    - Sname
    - Sid

The syntax for creating an attribute is:
    
    self.attribute = something
    
There is a special method called:

    __init__()

which is used to initialize the attributes of an object. For example:


In [100]:
class Student:
    def __init__(self,Sname,Sid):
        self.Sname = Sname
        self.Sid = Sid


#Object/Instance 1 of Student class with different attribute
manan = Student(Sname="manan",Sid=2)
manan.Sname
# manan.Sid


'manan'

In [101]:
#Object/Instance 2 of Student class with different attribute
Ram = Student(Sname="Ram",Sid=2)
Ram.Sname
# Ram.Sid

'Ram'

Lets break down what we have above.The special method

    __init__() 

is called automatically right after the object has been created:

    def __init__(self, Sname):
Each attribute in a class definition begins with a reference to the instance object. It is by convention named self. The Sname is the argument. The value is passed during the class instantiation.

     self.Sname = Sname
Now we have created two instances of the Student class. With two Sname types, we can then access these attributes like this:     

### Methods
- methods are those that define in class it's function but we call function that are in classe method

In [102]:
class Myclass(object):
    res = "pass"
    def __init__(self,sid,sname):
        self.sname = sname
        self.sid = sid

    def details(self):
        return f"name of student is {self.sname} and RollNo is {self.sid}"

    def result(self):
        return f"Result is {Myclass.res}"

stud1 = Myclass(sid=12,sname="manan")
stud1.details()


'name of student is manan and RollNo is 12'

In [103]:
stud1.result()

'Result is pass'

## Instance vs Class vs Static Methods
***
- Instance methods have access to the **instance** of the class
- Class methods have access to the **class** (classes are also objects in Python), but not instances. This is similar to the static methods in Java/C#
- Static methods have no access to either instances or classes. They are more like plain functions, just bounded with the class for scop

- in below example class variable is same for all instance or anything it's like static

- But instance variable change according to instance like stud1 have name manan and sid is 12 so for stud1 details are those
  but if stud2 name instance have changed value for that instance instance variable values changed 

In [104]:
class Myclass(object):
    res = "pass"# class variable

    #constructor
    def __init__(self,sid,sname):
        self.sname = sname
        self.sid = sid

    #instance variable
    def details(self):
        return f"name of student is {self.sname} and RollNo is {self.sid}"

    def result(self):
        return f"Result is {Myclass.res}"

    @classmethod
    def change_res(cls,changed_res):
        Myclass.res = changed_res

    @staticmethod
    def semester(sem):
        return f'result for semeter {sem}'

stud1 = Myclass(sid=12,sname="manan")
stud1.result()

'Result is pass'

**i wanna change result but "res" variable is class variable so it's static we can use @classmethod and 'cls' keyword like we do in 'self' instance method**

**Also if i wanna show one static variable that is static for all things i can make via @staticmethod and it don't need 'self or cls' just like simple function**

In [105]:
Myclass.change_res(changed_res="fail")

In [106]:
stud2 = Myclass(sid=1,sname="meet")
stud2.result()

'Result is fail'

In [107]:
Myclass.semester(sem=3)

'result for semeter 3'

## Example 2 Banking

In [108]:
class Bank:
    #class variable
    bank_name = "SBI"

    #construtor
    def __init__(self,account_holder: str,account_number: int,balance=0):
        self.account_holder = account_holder
        self.account_number = account_number
        self.balance = balance


    def deposit(self,amount):
        self.amount = amount
        if amount < 0:
            return "give valid number"
        else:
            self.balance += amount
        
        return f'your balance is {self.balance}'


    def withdraw(self,amount):
        self.amount = amount
        if amount < 0:
            return "give valid number"
        else:
            self.balance -= amount
        
        return f'your balance is {self.balance}'

    def account_details(self):
        return (f"Account Holder: {self.account_holder} \t" 
                f"Account Number: {self.account_number} \t" 
                f"Balance: {self.balance} \t" 
        f"Bank Name: {Bank.bank_name}")


    
    @classmethod
    def change_bankName(cls, new_name):
        cls.bank_name = new_name
        return f'Bank is {Bank.bank_name}'


    @staticmethod
    def bank_policies():
        return "The bank operates from 9 AM to 5 PM, Monday to Friday."

    def __add__(self,other):
        return f'{self.bank_name} + {other.bank_name}'


    def __str__(self):
        return f'hello {self.account_holder} Your Balance is {self.balance}'

account1 = Bank(account_holder="manan",account_number="2343242124",balance=20000)
account2 = Bank(account_holder="abhi",account_number="23421342144",balance=10000)


In [109]:
account1.account_details()

'Account Holder: manan \tAccount Number: 2343242124 \tBalance: 20000 \tBank Name: SBI'

In [110]:
account1.deposit(2000)

'your balance is 22000'

In [111]:
account1.withdraw(1000)

'your balance is 21000'

In [112]:
account1.balance

21000

In [113]:
account1.change_bankName("ICICI")

'Bank is ICICI'

In [114]:
account1.account_details()

'Account Holder: manan \tAccount Number: 2343242124 \tBalance: 21000 \tBank Name: ICICI'

In [115]:
account1.bank_policies()

'The bank operates from 9 AM to 5 PM, Monday to Friday.'

### Let's Do something deep in classes and OOP

- we see most of things like 
- **classes** 
- **making object of that class and** 
- **self keyword that use when you create object of class and use information that we declare in *__ init __* dunder method**
- **Then we see making methods of class so we can make some use of that class**

*But now let see some more magic methods that maybe usefull it's magic method cause it's built in python and it has *__ method __* type of naming*

In [116]:
#we have two objects with diff info of one class 
print(account1.account_details())
print(account2.account_details())

#now one account have bankname ICICI and i wanna add it in SBI but it;s object so how can we do that \
#we have __add__ dunder method for this 

print(account1 + account2) #unsupported operand type(s) for +: 'Bank' and 'Bank' :(
#now it show ICIC + ICICI so you can use * | anything all dunder methods are in __mul__ ...

#but let;s see some that usefull like when i print account1 simple it;s show something in <memory addr> but let's do some good looking thing not just memory address
print(account1) #hello manan Your Balance is 20000
print(account2) #hello abhi Your Balance is 10000

Account Holder: manan 	Account Number: 2343242124 	Balance: 21000 	Bank Name: ICICI
Account Holder: abhi 	Account Number: 23421342144 	Balance: 10000 	Bank Name: ICICI
ICICI + ICICI
hello manan Your Balance is 21000
hello abhi Your Balance is 10000


![caption](images/numpy-logo.jpg)


In [117]:
import numpy
numpy.array

ModuleNotFoundError: No module named 'numpy'

**here we are simply converting any list,tuple to array by using numpy finction array() and it's type is ndarray**

In [72]:
import numpy as np 

list1 = [10,20,40]
print(np.array(list1))
print(type(np.array(list1)))

[10 20 40]
<class 'numpy.ndarray'>


In [73]:
import numpy as np 

#2d array
list2 = [[10,20,30],[40,50,60],[70,80,90]]
np.array(list2)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## Types

![NumPy Array Types](images/numpy-types1.jpg)

`ndarray` is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an `ndarray` object are:

***ndarray.shape***
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, `shape` will be `(n,m)`. The length of the `shape` tuple is therefore the rank, or number of dimensions,`ndim`.

***ndarray.dtype***
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

***ndarray.reshape***
Returns an array containing the same data with a new shape.

### ndarray.dtype

In [74]:
import numpy as np

mylist = [10.2,20.4,30.5]
arr = np.array(mylist)

print(arr.dtype)

float64


### ndarray.shape

In [75]:
import numpy as np

#2d
mylist = [[10,20,30],[40,50,60,]]
arr = np.array(mylist)
print(arr.shape)



#3d
mylist2 = [[[10,20,30],[40,50,60,],[43,55,64,]],[[34,54,56],[32,53,67],[3,2,5]]]
arr2 = np.array(mylist2)
print(arr2.shape)

(2, 3)
(2, 3, 3)


### arange

In [76]:
import numpy as np

#for making array of some range and we can give steps 
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### zeros and ones

In [77]:
#for creating default matrix with zero and one value
import numpy as np

arr = np.zeros((2,3))
print(arr)
print("\n")
arr2 = np.ones((3,4))
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### linespace

```numpy.linspace(start, stop, num, endpoint=True, retstep=False, dtype=None, axis=0)```


*You’re planning to run a 10 km marathon, and you want to mark points every 2.5 km for water breaks. You’ll divide the 0 to 10 km stretch into equal segments:*
- Starting point: 0 km
- Water break points: 2.5 km, 5 km, 7.5 km, and finally, 10 km.

In [78]:
# divide into 7 interval from 0 to 10
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])



## How do I generate Random Numbers?
***
<br/>
Numpy also has lots of ways to create random number arrays of given shape

- **`rand`**:

`numpy.random.rand(d0, d1, …, dn)` Create an array of the given shape and populate it with random samples from a **uniform distribution**

- **`randn`**: 

`numpy.random.randn(d0, d1, …, dn)`creates an array of specified shape and fills it with random values as per **standard normal distribution**.

If positive arguments are provided, randn generates an array of shape (d0, d1, …, dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation).

A single float randomly sampled from the distribution is returned if no argument is provided.

- **`randint`**: 

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

In [79]:
# random number (uniform distribution) array of shape (3 , 4)

np.random.rand(2,3)

array([[0.77478599, 0.6841074 , 0.85637014],
       [0.88172397, 0.04541254, 0.84393722]])

In [80]:
# random number (standard normal distribution) array of shape (2, 3)

np.random.randn(2,3)

array([[-0.61920209,  0.20174762, -0.13259495],
       [-1.74973406,  0.23588972,  0.74355233]])

In [81]:
# 10 random integers between 4 (inclusive) to 40 (exclusive)

#genrate 10 random num between 4 to 40
np.random.randint(4,40,10)

array([19,  8,  9, 19, 27, 19, 31, 20, 17, 16])

In [82]:
# 10 random integers upto 50 (exclusive). This makes the start value default to 0.
# The size parameter dictates the return array shape

np.random.randint(50, size=(4,4))

array([[42, 47, 39,  6],
       [ 9, 30, 21, 25],
       [34, 45,  1, 34],
       [30, 34, 23,  1]])

# Introduction to
***
![Pandas_logo](images/pandas.png)
Image source:https://en.wikipedia.org/wiki/Pandas_(software)
***
The most widely used Python library for data science

## Why Pandas ?
***
<center>
<img src="images/why-pandas.jpg" width="50%"/>
</center>

## Features of Pandas
***
<center>
<img src="images/pandas-features.jpg" width="50%"/>
</center>


In [38]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [39]:
import pandas as pd

mylist = [1,3,43]
list_pd = pd.Series(mylist)
print(list_pd)

0     1
1     3
2    43
dtype: int64


In [40]:
tuple1 = (1,24,44)
tuple_pd = pd.Series(tuple1)
print(tuple_pd)

dict1 = {"key1":1,"key2":3}
dict_pd = pd.Series(dict1)
print(dict_pd) 
print(tuple_pd.index)
print(dict_pd.index)

0     1
1    24
2    44
dtype: int64
key1    1
key2    3
dtype: int64
RangeIndex(start=0, stop=3, step=1)
Index(['key1', 'key2'], dtype='object')


In [41]:
import numpy as np
arr = np.array(mylist)
print(arr)
nparr_pd = pd.Series(arr)
print(nparr_pd)

[ 1  3 43]
0     1
1     3
2    43
dtype: int64


In [42]:
ser1 = pd.Series(index=['USA','CAl','Uk'], data=['US1','CAl2','Uk2'])
ser1

USA     US1
CAl    CAl2
Uk      Uk2
dtype: object

In [43]:
import numpy as np
import pandas as pd

df = pd.DataFrame([[1,2,3],[2,34,55]])
df

0   1   2
0  1   2   3
1  2  34  55

In [44]:
import numpy as np
import pandas as pd

df = pd.DataFrame([[1,2,3],[2,34,55],[32,42,44]],index=['num1','num2','num3'],columns=['n1','n2','n3'])
print(df)
print(df.shape)


      n1  n2  n3
num1   1   2   3
num2   2  34  55
num3  32  42  44
(3, 3)


### Werher Project 

In [45]:
wether_df = pd.read_csv('weather_2012.csv')
print(f"shape : {wether_df.shape}")
print(f"index : {wether_df.index}")

shape : (8784, 8)
index : RangeIndex(start=0, stop=8784, step=1)


In [46]:
wether_df['Date/Time']

0       2012-01-01 00:00:00
1       2012-01-01 01:00:00
2       2012-01-01 02:00:00
3       2012-01-01 03:00:00
4       2012-01-01 04:00:00
               ...         
8779    2012-12-31 19:00:00
8780    2012-12-31 20:00:00
8781    2012-12-31 21:00:00
8782    2012-12-31 22:00:00
8783    2012-12-31 23:00:00
Name: Date/Time, Length: 8784, dtype: object

In [47]:
wether_df['Date/Time'].head()

0    2012-01-01 00:00:00
1    2012-01-01 01:00:00
2    2012-01-01 02:00:00
3    2012-01-01 03:00:00
4    2012-01-01 04:00:00
Name: Date/Time, dtype: object

In [48]:
type(wether_df['Date/Time'])

pandas.core.series.Series

In [49]:
wether_df['Date/Time'] = pd.to_datetime(wether_df['Date/Time'])

In [50]:
wether_df['Date/Time'].head()

0   2012-01-01 00:00:00
1   2012-01-01 01:00:00
2   2012-01-01 02:00:00
3   2012-01-01 03:00:00
4   2012-01-01 04:00:00
Name: Date/Time, dtype: datetime64[ns]

### .info()
### .index()
### .unique()
### .nunique()
### .value_conut()

In [51]:
wether_df['Date/Time'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 8784 entries, 0 to 8783
Series name: Date/Time
Non-Null Count  Dtype         
--------------  -----         
8784 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 68.8 KB


In [52]:
wether_df.head()

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0 2012-01-01 00:00:00      -1.8                -3.9           86   
1 2012-01-01 01:00:00      -1.8                -3.7           87   
2 2012-01-01 02:00:00      -1.8                -3.4           89   
3 2012-01-01 03:00:00      -1.5                -3.2           88   
4 2012-01-01 04:00:00      -1.5                -3.3           88   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                4              8.0           101.24                   Fog  
1                4              8.0           101.24                   Fog  
2                7              4.0           101.26  Freezing Drizzle,Fog  
3                6              4.0           101.27  Freezing Drizzle,Fog  
4                7              4.8           101.23                   Fog

In [53]:
wether_df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 

In [54]:
wether_df['Weather'].nunique()

50

In [55]:
wether_df['Weather'].value_counts()['Clear']

np.int64(1326)

## Data Maniupilate and Transform Data
***
The true power of the Pandas DataFrame is the ease and flexibility of manipulating data to get your desired results.

Pandas is best at handling tabular data sets comprising different variable types (integer, float, double, etc.). 

In addition, the pandas library can also be used to perform even the most naive of tasks such as loading data or doing feature engineering on time series data.

## Selection (Part 1)
***
How do you select particular rows/columns from the DataFrame ?

The DataFrame object supports indexing operations just like the Python `list` class and the Pandas Series object, but is much faster and more powerful.

Note that when you extract a single row or column, you get a one-dimensional object as output. That is called a pandas Series. The values on the left are just labels taken from the dataframe index. 

On the other hand, when we extract portions of a pandas dataframe, we get a two-dimensional DataFrame type of object. Something to keep in mind for later.

In [56]:
col = wether_df['Weather'] 

print(type(col))
col.head()



<class 'pandas.core.series.Series'>


0                     Fog
1                     Fog
2    Freezing Drizzle,Fog
3    Freezing Drizzle,Fog
4                     Fog
Name: Weather, dtype: object

In [57]:
multiple_col = wether_df[['Weather', 'Temp (C)']]
multiple_col

Weather  Temp (C)
0                      Fog      -1.8
1                      Fog      -1.8
2     Freezing Drizzle,Fog      -1.8
3     Freezing Drizzle,Fog      -1.5
4                      Fog      -1.5
...                    ...       ...
8779                  Snow       0.1
8780                  Snow       0.2
8781                  Snow      -0.5
8782                  Snow      -0.2
8783                  Snow       0.0

[8784 rows x 2 columns]

In [58]:
slicing_col = wether_df[:10]
slicing_col

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0 2012-01-01 00:00:00      -1.8                -3.9           86   
1 2012-01-01 01:00:00      -1.8                -3.7           87   
2 2012-01-01 02:00:00      -1.8                -3.4           89   
3 2012-01-01 03:00:00      -1.5                -3.2           88   
4 2012-01-01 04:00:00      -1.5                -3.3           88   
5 2012-01-01 05:00:00      -1.4                -3.3           87   
6 2012-01-01 06:00:00      -1.5                -3.1           89   
7 2012-01-01 07:00:00      -1.4                -3.6           85   
8 2012-01-01 08:00:00      -1.4                -3.6           85   
9 2012-01-01 09:00:00      -1.3                -3.1           88   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                4              8.0           101.24                   Fog  
1                4              8.0           101.24                   Fog  
2                7              4.0           101.26  Freezing Drizzle,Fog  
3                6              4.0           101.27  Freezing Drizzle,Fog  
4                7              4.8           101.23                   Fog  
5                9              6.4           101.27                   Fog  
6                7              6.4           101.29                   Fog  
7                7              8.0           101.26                   Fog  
8                9              8.0           101.23                   Fog  
9               15              4.0           101.20                   Fog

In [59]:
# solution 1
result1 = wether_df[:6:2][['Rel Hum (%)', 'Visibility (km)']]

# solution 2
result2 = wether_df[['Rel Hum (%)', 'Visibility (km)']][:6:2]

# are they the same?
print(result1)
print(result2)

result1 == result2

   Rel Hum (%)  Visibility (km)
0           86              8.0
2           89              4.0
4           88              4.8
   Rel Hum (%)  Visibility (km)
0           86              8.0
2           89              4.0
4           88              4.8


Rel Hum (%)  Visibility (km)
0         True             True
2         True             True
4         True             True

#### So which of the two solutions should you use?
***
**Answer**: Neither. Because we're indexing more than once (Chained Indexing).
When you use chained indexing, the order and type of the indexing operation partially determine whether the result is a slice into the original object, or a copy of the slice.

Let's analyse (break down) one of the above solutions.

In [60]:
# first indexing
df1 = wether_df[:6]

# second indexing
df2 = df1[['Rel Hum (%)', 'Visibility (km)']]

print(df1)
df2

            Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0 2012-01-01 00:00:00      -1.8                -3.9           86   
1 2012-01-01 01:00:00      -1.8                -3.7           87   
2 2012-01-01 02:00:00      -1.8                -3.4           89   
3 2012-01-01 03:00:00      -1.5                -3.2           88   
4 2012-01-01 04:00:00      -1.5                -3.3           88   
5 2012-01-01 05:00:00      -1.4                -3.3           87   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                4              8.0           101.24                   Fog  
1                4              8.0           101.24                   Fog  
2                7              4.0           101.26  Freezing Drizzle,Fog  
3                6              4.0           101.27  Freezing Drizzle,Fog  
4                7              4.8           101.23                   Fog  
5                9              6.4           101.27         

Rel Hum (%)  Visibility (km)
0           86              8.0
1           87              8.0
2           89              4.0
3           88              4.0
4           88              4.8
5           87              6.4

#### .loc()
#### .iloc()

##### Why not using slicing cause it's create copy of it so for larger dataset it might be defficult 

In [61]:
locdf = wether_df.loc[:5, ['Rel Hum (%)', 'Visibility (km)']]
print(locdf)

ilocdf = wether_df[['Rel Hum (%)', 'Visibility (km)']].iloc[0:5]
ilocdf


   Rel Hum (%)  Visibility (km)
0           86              8.0
1           87              8.0
2           89              4.0
3           88              4.0
4           88              4.8
5           87              6.4


Rel Hum (%)  Visibility (km)
0           86              8.0
1           87              8.0
2           89              4.0
3           88              4.0
4           88              4.8

**Here loc() purely based on label so 0:5 means in indexing label 0 to 5**
<br>
**And iloc() it's based on Index Location so it give 0:5 0 to 4 cause 0,1,2,3,4 is =5**


## Mini-Challenge - 4
***

Get the first 3 alternating rows from the `weather_df` dataframe, but only the Visibility and Relative Humidity columns


In [62]:
chall = wether_df[['Rel Hum (%)','Visibility (km)']].iloc[:5:2]
chall

Rel Hum (%)  Visibility (km)
0           86              8.0
2           89              4.0
4           88              4.8

# Phase 1 Of Transforming Data
##### Filtering
***

![Filter](images/filters1.jpg)
<br/>

Anything that takes in data, processes it, and provides an output

Input Data ⟶ Filter ⟶ Output Data

Filtering rows of a DataFrame is an almost mandatory task for Data Analysis with Python. Given a Data Frame, we may not be interested in the entire dataset but only in specific rows.

In [63]:
wether_df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 

**I need only snow data like snow weather only:))**

In [64]:
snowd_weather = wether_df['Weather'].str.lower().str.contains('snow')
snowd_weather

0       False
1       False
2       False
3       False
4       False
        ...  
8779     True
8780     True
8781     True
8782     True
8783     True
Name: Weather, Length: 8784, dtype: bool

In [65]:
wether_df['Weather'].iloc[4]

'Fog'

In [66]:
wether_df['Weather'].iloc[8780]

'Snow'

In [67]:
wether_df[snowd_weather]

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
41   2012-01-02 17:00:00      -2.1                -9.5           57   
44   2012-01-02 20:00:00      -5.6               -13.4           54   
45   2012-01-02 21:00:00      -5.8               -12.8           58   
47   2012-01-02 23:00:00      -7.4               -14.1           59   
48   2012-01-03 00:00:00      -9.0               -16.0           57   
...                  ...       ...                 ...          ...   
8779 2012-12-31 19:00:00       0.1                -2.7           81   
8780 2012-12-31 20:00:00       0.2                -2.4           83   
8781 2012-12-31 21:00:00      -0.5                -1.5           93   
8782 2012-12-31 22:00:00      -0.2                -1.8           89   
8783 2012-12-31 23:00:00       0.0                -2.1           86   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)       Weather  
41                 22             25.0            99.66  Snow Showers  
44                 24             25.0           100.07  Snow Showers  
45                 26             25.0           100.15  Snow Showers  
47                 17             19.3           100.27  Snow Showers  
48                 28             25.0           100.35  Snow Showers  
...               ...              ...              ...           ...  
8779               30              9.7           100.13          Snow  
8780               24              9.7           100.03          Snow  
8781               28              4.8            99.95          Snow  
8782               28              9.7            99.91          Snow  
8783               30             11.3            99.89          Snow  

[583 rows x 8 columns]

**DOne:))**

Now let's do some filtering practice 

Now i want In witch time/date wind speed is lesser than 5 and witch wether is there

In [68]:
#We get filter data by jusst doing one line code
wether_df[wether_df['Wind Spd (km/h)'] < 5]

# what we did is wether dataframe in that df we want filter data is like wind spd < 5 

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0    2012-01-01 00:00:00      -1.8                -3.9           86   
1    2012-01-01 01:00:00      -1.8                -3.7           87   
96   2012-01-05 00:00:00      -8.8               -11.7           79   
97   2012-01-05 01:00:00      -7.5               -10.2           81   
101  2012-01-05 05:00:00      -7.0                -9.5           82   
...                  ...       ...                 ...          ...   
8768 2012-12-31 08:00:00      -8.6               -10.3           87   
8769 2012-12-31 09:00:00      -8.1                -9.6           89   
8770 2012-12-31 10:00:00      -7.4                -8.9           89   
8772 2012-12-31 12:00:00      -5.8                -7.5           88   
8773 2012-12-31 13:00:00      -4.6                -6.6           86   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)       Weather  
0                   4              8.0           101.24           Fog  
1                   4              8.0           101.24           Fog  
96                  4              9.7           100.32          Snow  
97                  0              9.7           100.29          Snow  
101                 4              4.0           100.19          Snow  
...               ...              ...              ...           ...  
8768                4              3.2           101.14  Snow Showers  
8769                4              2.4           101.09          Snow  
8770                4              6.4           101.05      Snow,Fog  
8772                4             12.9           100.78          Snow  
8773                4             12.9           100.63          Snow  

[785 rows x 8 columns]

In [69]:
# Now we Want just three columns wether date/time and wind spd

New_df = wether_df[['Date/Time','Weather','Wind Spd (km/h)']]

#here we have three columns new_df so we want wind spd < 5 results 
New_df[New_df['Wind Spd (km/h)'] < 5] 

Date/Time       Weather  Wind Spd (km/h)
0    2012-01-01 00:00:00           Fog                4
1    2012-01-01 01:00:00           Fog                4
96   2012-01-05 00:00:00          Snow                4
97   2012-01-05 01:00:00          Snow                0
101  2012-01-05 05:00:00          Snow                4
...                  ...           ...              ...
8768 2012-12-31 08:00:00  Snow Showers                4
8769 2012-12-31 09:00:00          Snow                4
8770 2012-12-31 10:00:00      Snow,Fog                4
8772 2012-12-31 12:00:00          Snow                4
8773 2012-12-31 13:00:00          Snow                4

[785 rows x 3 columns]

## Summary / Cheatsheet: Selection/Indexing/Filtering
***
This is a handy reminder for what syntax will get what result.

Syntax | Function | Remarks
:--- | :--- | :---
**`df['some_label']`** |  Get the (single) Column referenced by name `some_label` | A **str** is provided
**`df[['label1', 'label2']]`** | Get multiple columns referenced by given names | A **list** is provided 
**`df[start:end:step]`** | Get corresponding rows (same as list slicing) | A **slicing operator**<br/> is provided
**`df[boolean array/df]`** | Get corresponding rows (same as list slicing) | A **filter object** is provided
**`df.loc [row_sel, col_sel]`** | Select specified rows and columns (by labels) | 
**`df.iloc[row_sel, col_sel]`** | Select specified rows and columns (by index) | 


# Phase 2 Of Transforming Data
##### Working with Columns
***
- We will learn how to carry out Series operations on DataFrame Columns
- How to add or update columns within a DataFrame
- How to rename specific columns
- How to delete or drop a column that is no longer required for analysis

Now we seen how to filter out data and all but now we working with columns

In [157]:
print(wether_df['Wind Spd (km/h)'].head())

#+++++55555
wether_df['Wind Spd (km/h)'].head() + 5

0    4
1    4
2    7
3    6
4    7
Name: Wind Spd (km/h), dtype: int64


0     9
1     9
2    12
3    11
4    12
Name: Wind Spd (km/h), dtype: int64

In [158]:
multi_2 = wether_df['Visibility (km)'] + wether_df['Wind Spd (km/h)']
multi_2.head()

0    12.0
1    12.0
2    11.0
3    10.0
4    11.8
dtype: float64

## `.apply()`
***

apply() is like applying any py function `def func()` and apply this func to any column of df

In [159]:
def multi(value):
    return value * 2

In [160]:
mult_func = wether_df['Rel Hum (%)'].apply(multi)
print(wether_df['Rel Hum (%)'].head())

mult_func.head()

0    86
1    87
2    89
3    88
4    88
Name: Rel Hum (%), dtype: int64


0    172
1    174
2    178
3    176
4    176
Name: Rel Hum (%), dtype: int64

## `.describe()`
***

it's used in Data science most for give you std mean and other math thing

In [161]:
wether_df['Visibility (km)'].describe()

count    8784.000000
mean       27.664447
std        12.622688
min         0.200000
25%        24.100000
50%        25.000000
75%        25.000000
max        48.300000
Name: Visibility (km), dtype: float64

### `Addind and updating Columns`

In [162]:
wether_df

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0    2012-01-01 00:00:00      -1.8                -3.9           86   
1    2012-01-01 01:00:00      -1.8                -3.7           87   
2    2012-01-01 02:00:00      -1.8                -3.4           89   
3    2012-01-01 03:00:00      -1.5                -3.2           88   
4    2012-01-01 04:00:00      -1.5                -3.3           88   
...                  ...       ...                 ...          ...   
8779 2012-12-31 19:00:00       0.1                -2.7           81   
8780 2012-12-31 20:00:00       0.2                -2.4           83   
8781 2012-12-31 21:00:00      -0.5                -1.5           93   
8782 2012-12-31 22:00:00      -0.2                -1.8           89   
8783 2012-12-31 23:00:00       0.0                -2.1           86   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                   4              8.0           101.24                   Fog  
1                   4              8.0           101.24                   Fog  
2                   7              4.0           101.26  Freezing Drizzle,Fog  
3                   6              4.0           101.27  Freezing Drizzle,Fog  
4                   7              4.8           101.23                   Fog  
...               ...              ...              ...                   ...  
8779               30              9.7           100.13                  Snow  
8780               24              9.7           100.03                  Snow  
8781               28              4.8            99.95                  Snow  
8782               28              9.7            99.91                  Snow  
8783               30             11.3            99.89                  Snow  

[8784 rows x 8 columns]

In [163]:
#make variable then add column
visibility_less = wether_df['Visibility (km)'] > 5
visibility_in_meter = wether_df['Visibility (km)'] * 1000 
wether_df['Visibility (less 5)'] = visibility_less
wether_df.head()

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0 2012-01-01 00:00:00      -1.8                -3.9           86   
1 2012-01-01 01:00:00      -1.8                -3.7           87   
2 2012-01-01 02:00:00      -1.8                -3.4           89   
3 2012-01-01 03:00:00      -1.5                -3.2           88   
4 2012-01-01 04:00:00      -1.5                -3.3           88   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  \
0                4              8.0           101.24                   Fog   
1                4              8.0           101.24                   Fog   
2                7              4.0           101.26  Freezing Drizzle,Fog   
3                6              4.0           101.27  Freezing Drizzle,Fog   
4                7              4.8           101.23                   Fog   

   Visibility (less 5)  
0                 True  
1                 True  
2                False  
3                False  
4                False

### `Renameing Column`

`.rename()`
for renaming we use Dict() structure so `old name : new name`

In [164]:
wether_df.rename(columns={'Visibility (m)':'Visibility (meters)'},inplace=True)
wether_df
#inplace = True is for it's update in Df itself if we don't put we have to store rename thing to var than give to Df

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0    2012-01-01 00:00:00      -1.8                -3.9           86   
1    2012-01-01 01:00:00      -1.8                -3.7           87   
2    2012-01-01 02:00:00      -1.8                -3.4           89   
3    2012-01-01 03:00:00      -1.5                -3.2           88   
4    2012-01-01 04:00:00      -1.5                -3.3           88   
...                  ...       ...                 ...          ...   
8779 2012-12-31 19:00:00       0.1                -2.7           81   
8780 2012-12-31 20:00:00       0.2                -2.4           83   
8781 2012-12-31 21:00:00      -0.5                -1.5           93   
8782 2012-12-31 22:00:00      -0.2                -1.8           89   
8783 2012-12-31 23:00:00       0.0                -2.1           86   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  \
0                   4              8.0           101.24                   Fog   
1                   4              8.0           101.24                   Fog   
2                   7              4.0           101.26  Freezing Drizzle,Fog   
3                   6              4.0           101.27  Freezing Drizzle,Fog   
4                   7              4.8           101.23                   Fog   
...               ...              ...              ...                   ...   
8779               30              9.7           100.13                  Snow   
8780               24              9.7           100.03                  Snow   
8781               28              4.8            99.95                  Snow   
8782               28              9.7            99.91                  Snow   
8783               30             11.3            99.89                  Snow   

      Visibility (less 5)  
0                    True  
1                    True  
2                   False  
3                   False  
4                   False  
...                   ...  
8779                 True  
8780                 True  
8781                False  
8782                 True  
8783                 True  

[8784 rows x 9 columns]

### Deleting Columns

## `.drop()`
***

Return new object with labels in requested axis removed.

Note that Pandas uses zero based numbering, so 0 is the first row, 1 is the second row, etc.
You can select ranges relative to the top or drop relative to the bottom of the DataFrame as well.

- Note: Specifying both labels and index or columns will raise a ValueError.

In [165]:
# from DF drop where lable= and on axis=1 means it's column we wanna drop
# wether_df.drop(labels=['Visibility (meters)'],axis=1).head()
wether_df.drop(labels=['Visibility (less 5)'],axis=1).head()


Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0 2012-01-01 00:00:00      -1.8                -3.9           86   
1 2012-01-01 01:00:00      -1.8                -3.7           87   
2 2012-01-01 02:00:00      -1.8                -3.4           89   
3 2012-01-01 03:00:00      -1.5                -3.2           88   
4 2012-01-01 04:00:00      -1.5                -3.3           88   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                4              8.0           101.24                   Fog  
1                4              8.0           101.24                   Fog  
2                7              4.0           101.26  Freezing Drizzle,Fog  
3                6              4.0           101.27  Freezing Drizzle,Fog  
4                7              4.8           101.23                   Fog

In [166]:
wether_df

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0    2012-01-01 00:00:00      -1.8                -3.9           86   
1    2012-01-01 01:00:00      -1.8                -3.7           87   
2    2012-01-01 02:00:00      -1.8                -3.4           89   
3    2012-01-01 03:00:00      -1.5                -3.2           88   
4    2012-01-01 04:00:00      -1.5                -3.3           88   
...                  ...       ...                 ...          ...   
8779 2012-12-31 19:00:00       0.1                -2.7           81   
8780 2012-12-31 20:00:00       0.2                -2.4           83   
8781 2012-12-31 21:00:00      -0.5                -1.5           93   
8782 2012-12-31 22:00:00      -0.2                -1.8           89   
8783 2012-12-31 23:00:00       0.0                -2.1           86   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  \
0                   4              8.0           101.24                   Fog   
1                   4              8.0           101.24                   Fog   
2                   7              4.0           101.26  Freezing Drizzle,Fog   
3                   6              4.0           101.27  Freezing Drizzle,Fog   
4                   7              4.8           101.23                   Fog   
...               ...              ...              ...                   ...   
8779               30              9.7           100.13                  Snow   
8780               24              9.7           100.03                  Snow   
8781               28              4.8            99.95                  Snow   
8782               28              9.7            99.91                  Snow   
8783               30             11.3            99.89                  Snow   

      Visibility (less 5)  
0                    True  
1                    True  
2                   False  
3                   False  
4                   False  
...                   ...  
8779                 True  
8780                 True  
8781                False  
8782                 True  
8783                 True  

[8784 rows x 9 columns]



## Sorting
***

## `.sort_values()`
***

Sort by the values along either axis, in a user specified order. The order can be specified by selecting true or false for the "ascending" parameter.

In [167]:
wether_df[['Temp (C)','Weather']].value_counts().sort_values(ascending=True)

Temp (C)  Weather      
-18.0     Cloudy            1
 30.7     Mostly Cloudy     1
 30.9     Clear             1
 31.1     Clear             1
          Mostly Cloudy     1
                           ..
 23.2     Mainly Clear     16
 3.7      Cloudy           16
 21.8     Mainly Clear     18
 24.2     Mainly Clear     18
 16.6     Mainly Clear     24
Name: count, Length: 2720, dtype: int64

# Phase 3 Of Transformation Data


### Pivot Tables : Excellent way to Summarize your Data!
***
- A pivot table is a tool that allows you to reorganize and summarize selected columns and rows of data in a dataframe <br/><br/>
- Pivot tables provide an easy way to subset by one column and then apply a calculation like a sum or a mean <br/><br/>
- Pivot tables first groups and only then applies a calculation

In [33]:
import pandas as pd
import numpy as np

data = {
    'A': ['John', 'Boby', 'Mina', 'Peter', 'Nicky'], # Name
    'B': ['Masters', 'Graduate', 'Graduate', 'Masters', 'Graduate'], # Profession
    'C': [23, 23, 21, 21, 24] # Age
}

ex_df = pd.DataFrame(data)
ex_df

A         B   C
0   John   Masters  23
1   Boby  Graduate  23
2   Mina  Graduate  21
3  Peter   Masters  21
4  Nicky  Graduate  24

Pivot tables take a large dataset, groups the data into buckets based on a specified attribute, and calculates summary information for each of those groups. Let’s say a shopkeeper was looking at a dataset with their daily sales for the year and then pivoted that data to show the average sales for each month.
<br>
So it has four things
- values
- index
- columns
- aggfunc(aggrenet function)

In [34]:
#it's for analysis data 

# now from above table i need sum of gradauate and master age and name so how can we do ??

#values=A? => cause we want aggregated names in one column
#index=['B'.'C']? => index are row so i need B and C row
#columns=['B']? => whcih column you need to group here B
pivot_df=ex_df.pivot_table(values='C',index=['C','B'],columns=['B'],aggfunc=np.sum)
pivot_df

/tmp/ipykernel_1007/2155123979.py:8: FutureWarning: The provided callable <function sum at 0x7ff2f424f060> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pivot_df=ex_df.pivot_table(values='C',index=['C','B'],columns=['B'],aggfunc=np.sum)


B           Graduate Masters
C  B                        
21 Graduate     Mina     NaN
   Masters       NaN   Peter
23 Graduate     Boby     NaN
   Masters       NaN    John
24 Graduate    Nicky     NaN

In [35]:
#for simple index 
pivot_df.reset_index()

B   C         B Graduate Masters
0  21  Graduate     Mina     NaN
1  21   Masters      NaN   Peter
2  23  Graduate     Boby     NaN
3  23   Masters      NaN    John
4  24  Graduate    Nicky     NaN

In [77]:
wether_df.head()

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0 2012-01-01 00:00:00      -1.8                -3.9           86   
1 2012-01-01 01:00:00      -1.8                -3.7           87   
2 2012-01-01 02:00:00      -1.8                -3.4           89   
3 2012-01-01 03:00:00      -1.5                -3.2           88   
4 2012-01-01 04:00:00      -1.5                -3.3           88   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                4              8.0           101.24                   Fog  
1                4              8.0           101.24                   Fog  
2                7              4.0           101.26  Freezing Drizzle,Fog  
3                6              4.0           101.27  Freezing Drizzle,Fog  
4                7              4.8           101.23                   Fog

In [94]:
mean_temp_df = wether_df.pivot_table(values='Temp (C)',index=wether_df['Date/Time'].dt.month,columns=[wether_df['Weather']],aggfunc=np.mean)
mean_temp_df

/tmp/ipykernel_1007/1176480173.py:1: FutureWarning: The provided callable <function mean at 0x7ff2f42704a0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  mean_temp_df = wether_df.pivot_table(values='Temp (C)',index=wether_df['Date/Time'].dt.month,columns=[wether_df['Weather']],aggfunc=np.mean)


Weather        Clear     Cloudy    Drizzle  Drizzle,Fog  \
Date/Time                                                 
1         -13.332468  -6.668276   3.300000     0.966667   
2          -6.491096  -2.684713   2.300000          NaN   
3           5.042581   3.333333   1.400000     3.042857   
4           3.716129   7.608475        NaN     7.600000   
5          14.710092  15.383824  14.600000    11.887500   
6          18.715789  19.331250  14.600000    13.150000   
7          19.350388  24.624324        NaN    19.900000   
8          21.013393  21.852577  18.800000          NaN   
9          13.915385  17.145902  11.385714    11.100000   
10          7.954217  12.928758  10.766667    10.630000   
11         -2.080851   2.458015   5.175000          NaN   
12         -9.087500  -2.484434   1.575000     3.383333   

Weather    Drizzle,Ice Pellets,Fog  Drizzle,Snow  Drizzle,Snow,Fog        Fog  \
Date/Time                                                                       
1                              NaN           NaN               NaN  -2.105556   
2                              NaN           NaN               NaN  -0.725000   
3                              NaN           NaN               NaN   2.640000   
4                              NaN           NaN               NaN   0.850000   
5                              NaN           NaN               NaN  10.350000   
6                              NaN           NaN               NaN        NaN   
7                              NaN           NaN               NaN  20.300000   
8                              NaN           NaN               NaN  19.950000   
9                              NaN           NaN               NaN  15.700000   
10                             NaN           NaN               NaN  12.302857   
11                             NaN           NaN               NaN  -2.788889   
12                             0.4          1.05          0.693333  -6.066667   

Weather    Freezing Drizzle  Freezing Drizzle,Fog  ...  Snow,Fog  Snow,Haze  \
Date/Time                                          ...                        
1                    -6.175                  -2.5  ...       NaN        NaN   
2                    -6.300                   NaN  ... -0.350000      -4.02   
3                       NaN                   NaN  ...  0.700000        NaN   
4                       NaN                   NaN  ...       NaN        NaN   
5                       NaN                   NaN  ...       NaN        NaN   
6                       NaN                   NaN  ...       NaN        NaN   
7                       NaN                   NaN  ...       NaN        NaN   
8                       NaN                   NaN  ...       NaN        NaN   
9                       NaN                   NaN  ...       NaN        NaN   
10                      NaN                   NaN  ...       NaN        NaN   
11                      NaN                   NaN  ...       NaN        NaN   
12                   -2.300                  -2.6  ... -6.524138        NaN   

Weather    Snow,Ice Pellets  Thunderstorms  Thunderstorms,Heavy Rain Showers  \
Date/Time                                                                      
1                       NaN            NaN                               NaN   
2                       NaN            NaN                               NaN   
3                      0.55            NaN                               NaN   
4                       NaN            NaN                               NaN   
5                       NaN            NaN                              10.9   
6                       NaN            NaN                               NaN   
7                       NaN          24.15                               NaN   
8                       NaN            NaN                               NaN   
9                       NaN            NaN                               NaN   
10                      NaN            NaN         

### Group By


***
The groupby method allows you to group rows of data together and call aggregate functions that applies to the whole group.

Any groupby operation involves one of the following operations on the original object. They are −
- Splitting the Object
- Applying a function
- Combining the results

In many situations, we split the data into sets and we apply some functionality on each subset. In the apply functionality, we can perform the following operations −

- Aggregation − computing a summary statistic
- Transformation − perform some group-specific operation
- Filtration − discarding the data with some condition

##### it's somewhat similer to pivot_table aggregating and making groups likewhat

In [105]:
wether_df

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0    2012-01-01 00:00:00      -1.8                -3.9           86   
1    2012-01-01 01:00:00      -1.8                -3.7           87   
2    2012-01-01 02:00:00      -1.8                -3.4           89   
3    2012-01-01 03:00:00      -1.5                -3.2           88   
4    2012-01-01 04:00:00      -1.5                -3.3           88   
...                  ...       ...                 ...          ...   
8779 2012-12-31 19:00:00       0.1                -2.7           81   
8780 2012-12-31 20:00:00       0.2                -2.4           83   
8781 2012-12-31 21:00:00      -0.5                -1.5           93   
8782 2012-12-31 22:00:00      -0.2                -1.8           89   
8783 2012-12-31 23:00:00       0.0                -2.1           86   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                   4              8.0           101.24                   Fog  
1                   4              8.0           101.24                   Fog  
2                   7              4.0           101.26  Freezing Drizzle,Fog  
3                   6              4.0           101.27  Freezing Drizzle,Fog  
4                   7              4.8           101.23                   Fog  
...               ...              ...              ...                   ...  
8779               30              9.7           100.13                  Snow  
8780               24              9.7           100.03                  Snow  
8781               28              4.8            99.95                  Snow  
8782               28              9.7            99.91                  Snow  
8783               30             11.3            99.89                  Snow  

[8784 rows x 8 columns]

In [109]:
# mean_temp_df = wether_df.pivot_table(values='Temp (C)',index=wether_df['Date/Time'].dt.month,columns=[wether_df['Weather']],aggfunc=np.mean)
# mean_temp_df

## - in pivot table we just found mean temps in every month so let's do same
wether_df.groupby(wether_df['Date/Time'].dt.month).agg({"Temp (C)" : "mean",})

Temp (C)
Date/Time           
1          -7.371505
2          -4.225000
3           3.121237
4           7.009306
5          16.237769
6          20.134028
7          22.790054
8          22.279301
9          16.484444
10         10.954973
11          0.931389
12         -3.306317