In [1]:
print("Hello Data World")

Hello Data World


<img src="images/py.png" id="string" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br /> 

# Strings
***

Strings are used in Python to record text information, such as name. Strings in Python are actually a *sequence*, which basically means Python keeps track of every element in the string as a sequence. For example, Python understands the string "Python' to be a sequence of letters in a specific order. This means we will be able to use indexing to grab particular letters (like the first letter, or the last letter).

<img src="images/python_string.png" id="string" alt="Concept-Alert" style="float:center; "/>
<br/>
<br/>


This idea of a sequence is an important one in Python and we will touch upon it later on in the future.

In this lecture we'll learn about the following:

    1.) Creating Strings
    2.) Printing Strings
    3.) String Indexing and Slicing
    4.) String Properties
    5.) String Methods
    6.) Print Formatting

In [2]:
print("hello")
print() #line space
print("hello world")

hello

hello world


In [3]:
str1 = "hello"
str2 = "world"
# str1[0]
# str1[1]
# str1[2]
# str1[3]
# str1[4]
str1[-5]
str1[-4]
str1[-3]
str1[-2]
str1[-1]
print(str1+' '+str2)
# print(str1 * 10)
print('-' * 10)

hello world
----------




## String Slicing & Indexing
***
**String Indexing** is used to to select the letter at a particular index/position. 

**String Slicing** is a process to select a subset of an entire string

<img src="images/string-slicing-in-python.png" alt="Concept-Alert" style="float:center;" width="600px" height="400px"/> 
<br /> 

The examples of the above stated are as follows

In [4]:
s = "Namaste world"
s[0] # indexing
s[0:7] # slicing
s[0:] # slicing 0 to end
# s[0:7:2] # slicing with step
print('world' in s) # checking if a string is present in another string

True


### **Basic Built in String Python Functions**

In [9]:
a = "hello world"

print(a.upper())
print(a.lower())
print(type(a))

HELLO WORLD
hello world
<class 'str'>


In [12]:
# Formattig

name = "Manan"
age = 25
married = False

print("My name is %s and I am %d years old. %s" % (name, age,married))
print("My name is {} and I am {} years old. {}".format(name, age,married))

print(f"My name is {name} and I am {age} years old. {married}")

My name is Manan and I am 25 years old. False
My name is Manan and I am 25 years old. False
My name is Manan and I am 25 years old. False


# Working with Numbers

In [19]:
#Int and float 

print(2+3)
print(type(2+3)) 
print(type(2+3.2)) 

5
<class 'int'>
<class 'float'>


In [20]:
2 + 10 * 10 + 3

105

In [25]:
15 * 2 + 10

40

In [ ]:
a = 10 
b = 20 
#mean means average
mean = (a + b) / 2 
print(mean)

15.0




# Lists
***
Lists can be thought of the most general version of a *sequence* in Python. 

In this section we will learn about:
    
    1.) Creating lists
    2.) Indexing and Slicing Lists
    3.) Basic List Methods
    4.) Nesting Lists
    5.) Introduction to List Comprehensions
    
<img src="images/python-list.jpeg" id="list" alt="Concept-Alert" style="float:center; margin-right:15px" width="700px" height="400px"/>
<br /> 

Lists are constructed with brackets [] and commas separating every element in the list.

Let's go ahead and see how we can construct lists!

In [28]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list3 = [11,12,13,14,15]

list4 = [list1,list2,list3]
print(list4)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]


#### Adding element 

In [7]:
l = [1,2,2.3,"one",'h']
l.append('e')
print(l)

[1, 2, 2.3, 'one', 'h', 'e']


Difference between append and extend

In [ ]:
l =  [1,2,3]
print(l)
#now if i append and list 
l.append([4,5,6])
print(l)

#look at the output it has whole list as an single index
print(l[3])
# it just append the item not extent the list 

[1, 2, 3]
[1, 2, 3, [4, 5, 6]]
[4, 5, 6]


In [ ]:
l = [1,2,3]
l.extend([4,5,6])
l
# now look at the output it extend list 

[1, 2, 3, 4, 5, 6]

In [ ]:
l = list(range(10))
l
l[0:2]
l[0:10:2] #start:end:step



[0, 2, 4, 6, 8]


# Dictionaries
***
Now we're going to switch gears and learn about *mappings* called *dictionaries* in Python. If you're familiar with other languages you can think of these Dictionaries as hash tables. 

This section will serve as a brief introduction to dictionaries and consist of:

    1.) Constructing a Dictionary
    2.) Accessing objects from a dictionary
    3.) Nesting Dictionaries
    4.) Basic Dictionary Methods

<img src="images/dictionaries-in-python.jpeg" id = "dict" alt="Concept-Alert" style="float:center; margin-right:15px" width="600" height="400"/>
<br /> 

A Python dictionary consists of a key and then an associated value. That value can be almost any Python object.


## Constructing a Dictionary
Let's see how we can construct dictionaries to get a better understanding of how they work!

In [ ]:
d = dict()
d['name'] = 'Manan'
d['age'] = 25
d['city'] = 'New Delhi'
print(d)

#################################
d2 = {'name': 'Manan', 'age': 25, 'city': 'New Delhi'}
d2

{'name': 'Manan', 'age': 25, 'city': 'New Delhi'}


{'name': 'Manan', 'age': 25, 'city': 'New Delhi'}

In [36]:
d2 = {'name': 'Manan', 'age': 25, 'city': 'New Delhi'}
d2['name'] == 'Manan'

d3 = {'name': 'Manan', 'age': [25,23,2], 'city': ['New Delhi', 'Mumbai']}
d3['age']

d3['age'][0]

d3['name'] += 'Pujara'
d3

d3['contact'] = {'phone': '9876543210', 'email': 'manan@gmail.com'}
d3

{'name': 'MananPujara',
 'age': [25, 23, 2],
 'city': ['New Delhi', 'Mumbai'],
 'contact': {'phone': '9876543210', 'email': 'manan@gmail.com'}}

# Set and Booleans
***
There are two other object types in Python that we should quickly cover. Sets and Booleans. 

## Sets

Sets are an unordered collection of *unique* elements. We can construct them by using the set() function. Let's go ahead and make a set to see how it works

#### Set Theory
<img src="images/sets2.png" width="40%"/>

In [37]:
l = [1,1,1,2,2,2,2,2,4,4,4,4]
l

[1, 1, 1, 2, 2, 2, 2, 2, 4, 4, 4, 4]

In [38]:
l_set = set(l)
l_set

{1, 2, 4}

##### Look above output set remove duplicate values

In [40]:
s = set()
s.add(1)
s

{1}

In [43]:
s.add(2)
s.add(3)
s

{1, 2, 3}

In [ ]:
s.add(2)
s
# it will not add the number 2 to the set

{1, 2, 3}


# Python Tuples
***
Tuples are used to store multiple items in a single variable.

Tuple is one of 4 built-in data types in Python used to store collections of data, the other 3 are List, Set, and Dictionary, all with different qualities and usage.

A tuple is a collection which is ordered and unchangeable.

Tuples are written with round brackets.

In [ ]:
t = (1,2,2,2,2,3,4,5,6,7,8,9,10)
t
print(type(t))


<class 'tuple'>


1

Tuple items are ordered, unchangeable, and allow duplicate values.

Tuple items are indexed, the first item has index [0], the second item has index [1] etc.

TypeError: 'tuple' object does not support item assignment

<img src='images/data_struc.png' width="800">

## Comprehensions
***
- Python provides syntactic sugar to write small loops to generate lists/sets/tuples/dicts in one line
- These are called comprehensions, and can greatly increase development speed and readability

Syntax:
```
    sequence = [expression(element) for element in iterable if condition]
```

The brackets used for creating the comprehension define what type of object is created.

Use **[ ]** for lists, **()** for _generators_, **{}** for sets and dicts

In [2]:
names = ['John', 'Mary', 'Peter', 'Paul', 'George', 'Ringo']
for name in names:
    print(f"hello {name}")



hello John
hello Mary
hello Peter
hello Paul
hello George
hello Ringo


In [7]:
names = ['John', 'Mary', 'Peter', 'Paul', 'George', 'Ringo']
hello = ['hello '+ name for name in names]
hello

['hello John',
 'hello Mary',
 'hello Peter',
 'hello Paul',
 'hello George',
 'hello Ringo']

In [8]:
nums = [1,2,3,4,5,6,7,8,9,10]
num_even =[num for num in nums if num%2==0]
print(num_even)


nums = [1,2,3,4,5,6,7,8,9,10]
num_odd =[num for num in nums if num%2!=0]
print(num_odd)


[2, 4, 6, 8, 10]
[1, 3, 5, 7, 9]


In [5]:
nums = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]

squerenum = [num * num for num in nums]
squerenum

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

## Exception Handling
***
#### try and except

The basic terminology and syntax used to handle errors in Python is the **try** and **except** statements. The code which can cause an exception to occue is put in the *try* block and the handling of the exception is the implemented in the *except* block of code. The syntax form is:

<img src="images/try_except_else_finally.webp" width="50%">

We can also just check for any exception with just using except: To get a better understanding of all this lets check out an example: We will look at some code that opens and writes a file:

In [7]:
try:
    1/0
except ZeroDivisionError:
    print("Divide by zero")
    

Divide by zero


<img src="images/exception.png" width="50%">


## File I/O : Helps you read your files
***
- Python provides a `file` object to read text/binary files.
- This is similar to the `FileStream` object in other languages.
- Since a `file` is a resource, it must be closed after use. This can be done manually, or using a context manager (**`with`** statement)

<div class="alert alert-block alert-info">Create a file in the current directory</div>

In [16]:
with open("myfile.txt",'w') as f:
    f.write("This is My File \n")
    f.write("boom baam \n")

In [17]:
with open("myfile.txt",'a') as f:
    f.write("This is appended content \n")
    f.write("boom baam")

In [10]:
# let's verify if it was really created.
# For that, let's find out which directory we're working from

import os
print(os.path.abspath(os.curdir)) #os->path->absoulate path-> os.cureentdir

/home/manan/Desktop/DataEnginnerProjects/Py_For_DataEnginner


<div class="alert alert-block alert-info">Read the newly created file</div>

In [18]:
with open("myfile.txt",'r') as f:
    for line in f:
        print(line)

This is My File 

boom baam 

This is appended content 

boom baam


In [12]:
f.close()

In [19]:
with open("myfile.txt",'r') as f:
    for line in f:
        print(line)

This is My File 

boom baam 

This is appended content 

boom baam


# Lambda Function

##### it's just simpler version to make function in variable like you don;t need to write def and all thing

In [8]:
lambda_squere = lambda num:num**2
lambda_squere(2)

4

In [4]:
def squere(num):
    return num**2

squere(2)


4

# OOP 

- objects
- class
- attribute methon 
- special methods

## Object
look below we have all data type classes and we creating objects of it 

In [10]:
s = "manan"
i = 2
print(type(s))
print(type(i))
print(type([]))
print(type(()))
print(type({}))

<class 'str'>
<class 'int'>
<class 'list'>
<class 'tuple'>
<class 'dict'>


- we see that datatypes classes are pre defined or they already made by someone but let's see how we make our own class and make object of that

In [12]:
class Example:
    pass

x = Example()
print(type(x))

<class '__main__.Example'>


## Attribute 
it's what the object has like 
- Sudent class
    - Sname
    - Sid

The syntax for creating an attribute is:
    
    self.attribute = something
    
There is a special method called:

    __init__()

which is used to initialize the attributes of an object. For example:


In [26]:
class Student:
    def __init__(self,Sname,Sid):
        self.Sname = Sname
        self.Sid = Sid


#Object/Instance 1 of Student class with different attribute
manan = Student(Sname="manan",Sid=2)
manan.Sname
# manan.Sid


'manan'

In [25]:
#Object/Instance 2 of Student class with different attribute
Ram = Student(Sname="Ram",Sid=2)
Ram.Sname
# Ram.Sid

'Ram'

Lets break down what we have above.The special method

    __init__() 

is called automatically right after the object has been created:

    def __init__(self, Sname):
Each attribute in a class definition begins with a reference to the instance object. It is by convention named self. The Sname is the argument. The value is passed during the class instantiation.

     self.Sname = Sname
Now we have created two instances of the Student class. With two Sname types, we can then access these attributes like this:     

### Methods
- methods are those that define in class it's function but we call function that are in classe method

In [32]:
class Myclass(object):
    res = "pass"
    def __init__(self,sid,sname):
        self.sname = sname
        self.sid = sid

    def details(self):
        return f"name of student is {self.sname} and RollNo is {self.sid}"

    def result(self):
        return f"Result is {Myclass.res}"

stud1 = Myclass(sid=12,sname="manan")
stud1.details()


'name of student is manan and RollNo is 12'

In [31]:
stud1.result()

'Result is pass'

## Instance vs Class vs Static Methods
***
- Instance methods have access to the **instance** of the class
- Class methods have access to the **class** (classes are also objects in Python), but not instances. This is similar to the static methods in Java/C#
- Static methods have no access to either instances or classes. They are more like plain functions, just bounded with the class for scop

- in below example class variable is same for all instance or anything it's like static

- But instance variable change according to instance like stud1 have name manan and sid is 12 so for stud1 details are those
  but if stud2 name instance have changed value for that instance instance variable values changed 

In [44]:
class Myclass(object):
    res = "pass"# class variable

    #constructor
    def __init__(self,sid,sname):
        self.sname = sname
        self.sid = sid

    #instance variable
    def details(self):
        return f"name of student is {self.sname} and RollNo is {self.sid}"

    def result(self):
        return f"Result is {Myclass.res}"

    @classmethod
    def change_res(cls,changed_res):
        Myclass.res = changed_res

    @staticmethod
    def semester(sem):
        return f'result for semeter {sem}'

stud1 = Myclass(sid=12,sname="manan")
stud1.result()

'Result is pass'

**i wanna change result but "res" variable is class variable so it's static we can use @classmethod and 'cls' keyword like we do in 'self' instance method**

**Also if i wanna show one static variable that is static for all things i can make via @staticmethod and it don't need 'self or cls' just like simple function**

In [36]:
Myclass.change_res(changed_res="fail")

In [37]:
stud2 = Myclass(sid=1,sname="meet")
stud2.result()

'Result is fail'

In [45]:
Myclass.semester(sem=3)

'result for semeter 3'

## Example 2 Banking

In [20]:
class Bank:
    #class variable
    bank_name = "SBI"

    #construtor
    def __init__(self,account_holder: str,account_number: int,balance=0):
        self.account_holder = account_holder
        self.account_number = account_number
        self.balance = balance


    def deposit(self,amount):
        self.amount = amount
        if amount < 0:
            return "give valid number"
        else:
            self.balance += amount
        
        return f'your balance is {self.balance}'


    def withdraw(self,amount):
        self.amount = amount
        if amount < 0:
            return "give valid number"
        else:
            self.balance -= amount
        
        return f'your balance is {self.balance}'

    def account_details(self):
        return (f"Account Holder: {self.account_holder} \t" 
                f"Account Number: {self.account_number} \t" 
                f"Balance: {self.balance} \t" 
        f"Bank Name: {Bank.bank_name}")


    
    @classmethod
    def change_bankName(cls, new_name):
        cls.bank_name = new_name
        return f'Bank is {Bank.bank_name}'


    @staticmethod
    def bank_policies():
        return "The bank operates from 9 AM to 5 PM, Monday to Friday."

    def __add__(self,other):
        return f'{self.bank_name} + {other.bank_name}'


    def __str__(self):
        return f'hello {self.account_holder} Your Balance is {self.balance}'

account1 = Bank(account_holder="manan",account_number="2343242124",balance=20000)
account2 = Bank(account_holder="abhi",account_number="23421342144",balance=10000)


In [2]:
account1.account_details()

'Account Holder: manan \tAccount Number: 2343242124 \tBalance: 20000 \tBank Name: SBI'

In [4]:
account1.deposit(2000)

'your balance is 21000'

In [3]:
account1.withdraw(1000)

'your balance is 19000'

In [15]:
account1.balance

21000

In [16]:
account1.change_bankName("ICICI")

'Bank is ICICI'

In [17]:
account1.account_details()

'Account Holder: manan \tAccount Number: 2343242124 \tBalance: 21000 \tBank Name: ICICI'

In [19]:
account1.bank_policies()

'The bank operates from 9 AM to 5 PM, Monday to Friday.'

### Let's Do something deep in classes and OOP

- we see most of things like 
- **classes** 
- **making object of that class and** 
- **self keyword that use when you create object of class and use information that we declare in *__ init __* dunder method**
- **Then we see making methods of class so we can make some use of that class**

*But now let see some more magic methods that maybe usefull it's magic method cause it's built in python and it has *__ method __* type of naming*

In [22]:
#we have two objects with diff info of one class 
print(account1.account_details())
print(account2.account_details())

#now one account have bankname ICICI and i wanna add it in SBI but it;s object so how can we do that \
#we have __add__ dunder method for this 

print(account1 + account2) #unsupported operand type(s) for +: 'Bank' and 'Bank' :(
#now it show ICIC + ICICI so you can use * | anything all dunder methods are in __mul__ ...

#but let;s see some that usefull like when i print account1 simple it;s show something in <memory addr> but let's do some good looking thing not just memory address
print(account1) #hello manan Your Balance is 20000
print(account2) #hello abhi Your Balance is 10000

Account Holder: manan 	Account Number: 2343242124 	Balance: 20000 	Bank Name: SBI
Account Holder: abhi 	Account Number: 23421342144 	Balance: 10000 	Bank Name: SBI
SBI + SBI
hello manan Your Balance is 20000
hello abhi Your Balance is 10000


![caption](images/numpy-logo.jpg)


In [3]:
import numpy
numpy.array

<function numpy.array>

**here we are simply converting any list,tuple to array by using numpy finction array() and it's type is ndarray**

In [6]:
import numpy as np 

list1 = [10,20,40]
print(np.array(list1))
print(type(np.array(list1)))

[10 20 40]
<class 'numpy.ndarray'>


In [10]:
import numpy as np 

#2d array
list2 = [[10,20,30],[40,50,60],[70,80,90]]
np.array(list2)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## Types

![NumPy Array Types](images/numpy-types1.jpg)

`ndarray` is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an `ndarray` object are:

***ndarray.shape***
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, `shape` will be `(n,m)`. The length of the `shape` tuple is therefore the rank, or number of dimensions,`ndim`.

***ndarray.dtype***
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

***ndarray.reshape***
Returns an array containing the same data with a new shape.

### ndarray.dtype

In [17]:
import numpy as np

mylist = [10.2,20.4,30.5]
arr = np.array(mylist)

print(arr.dtype)

float64


### ndarray.shape

In [35]:
import numpy as np

#2d
mylist = [[10,20,30],[40,50,60,]]
arr = np.array(mylist)
print(arr.shape)



#3d
mylist2 = [[[10,20,30],[40,50,60,],[43,55,64,]],[[34,54,56],[32,53,67],[3,2,5]]]
arr2 = np.array(mylist2)
print(arr2.shape)

(2, 3)
(2, 3, 3)


### arange

In [39]:
import numpy as np

#for making array of some range and we can give steps 
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### zeros and ones

In [45]:
#for creating default matrix with zero and one value
import numpy as np

arr = np.zeros((2,3))
print(arr)
print("\n")
arr2 = np.ones((3,4))
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### linespace

```numpy.linspace(start, stop, num, endpoint=True, retstep=False, dtype=None, axis=0)```


*You’re planning to run a 10 km marathon, and you want to mark points every 2.5 km for water breaks. You’ll divide the 0 to 10 km stretch into equal segments:*
- Starting point: 0 km
- Water break points: 2.5 km, 5 km, 7.5 km, and finally, 10 km.

In [50]:
# divide into 7 interval from 0 to 10
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])



## How do I generate Random Numbers?
***
<br/>
Numpy also has lots of ways to create random number arrays of given shape

- **`rand`**:

`numpy.random.rand(d0, d1, …, dn)` Create an array of the given shape and populate it with random samples from a **uniform distribution**

- **`randn`**: 

`numpy.random.randn(d0, d1, …, dn)`creates an array of specified shape and fills it with random values as per **standard normal distribution**.

If positive arguments are provided, randn generates an array of shape (d0, d1, …, dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation).

A single float randomly sampled from the distribution is returned if no argument is provided.

- **`randint`**: 

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

In [57]:
# random number (uniform distribution) array of shape (3 , 4)

np.random.rand(2,3)

array([[0.91445496, 0.92226811, 0.5065879 ],
       [0.3563332 , 0.72444484, 0.26073748]])

In [55]:
# random number (standard normal distribution) array of shape (2, 3)

np.random.randn(2,3)

array([[ 1.6244417 ,  1.46271253, -0.98819371],
       [ 1.05440289,  0.65114473,  1.02365298]])

In [69]:
# 10 random integers between 4 (inclusive) to 40 (exclusive)

#genrate 10 random num between 4 to 40
np.random.randint(4,40,10)

array([21, 21, 12, 12, 36, 36,  7, 26,  7,  6], dtype=int32)

In [78]:
# 10 random integers upto 50 (exclusive). This makes the start value default to 0.
# The size parameter dictates the return array shape

np.random.randint(50, size=(4,4))

array([[ 5, 27, 11, 44],
       [14, 46, 10, 35],
       [25, 14, 37, 34],
       [20,  3,  0,  8]], dtype=int32)

# Introduction to
***
![Pandas_logo](images/pandas.png)
Image source:https://en.wikipedia.org/wiki/Pandas_(software)
***
The most widely used Python library for data science